import express from "express";
import {getCourseModules,getModule,reorderAndAddModules,addModule,updateModule,deleteModule} from "../controllers/moduleController";
const router = express.Router();
router.get("/:courseId",getCourseModules);
router.get("/module/:moduleId",getModule);
router.patch("/:moduleId",updateModule);
router.delete("/:moduleId",deleteModule);
router.put("/:courseId",reorderAndAddModules);
router.post("/:courseId",addModule);
export default router;
