import { type Metadata } from 'next';
import {
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import Providers from './providers';
import Link from 'next/link';

// These styles apply to every route in the application
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <header className="flex justify-between items-center p-4 h-16 bg-white shadow-sm">
            <div className="flex items-center space-x-6">
              <Link href="/" className="text-2xl font-bold">
                NG-LMS
              </Link>
              <SignedIn>{/*if user signed in, display content inside*/}
                <nav className="flex space-x-4">
                  <Link href="/student" className="hover:underline">
                    Student
                  </Link>
                  <Link href="/teacher" className="hover:underline">
                    Teacher
                  </Link>
                  <Link href="/admin" className="hover:underline">
                    Admin
                  </Link>
                  <Link href="/manager" className="hover:underline">
                    Manager
                  </Link>
                </nav>
              </SignedIn>
            </div>
            <div className="flex items-center space-x-3">
              <SignedOut>{/*if user signed out, display content inside*/}
                <SignInButton>{/*click it will direct to sign-in[[...index]]/page.tsx path*/}
                  <button className="cursor-pointer rounded border border-gray-300 px-3 py-1">
                    Sign in
                  </button>
                </SignInButton>
                <SignUpButton>{/*click it will direct to sign-in[[...index]]/page.tsx path*/}
                  <button className="cursor-pointer rounded border border-gray-300 px-3 py-1">
                    Sign up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />{/*if signed in, display the button about user's information*/}
              </SignedIn>
            </div>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
